# Site settings
title: In The Weeds - Job Board
email:
description: > # this means to ignore newlines until "baseurl:"
  We are a community of designers and developers aiming to push more open design processes and improve the design of open source apps
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://intheweedsjobs.com" # the base hostname & protocol for your site
twitter_username: intheweedsjobs
github_username:  intheweedsjobs

# Build settings
markdown: kramdown
permalink: /:month-:day-:year/:title.html

kramdown:
  input: GFM
